### ISSUE TITLE
MacOSX compilation

### ISSUE THREAD

**Issue by predat** [MrKepzie/Natron#2]
I'm trying to compile on macosx 10.8 with Xcode 5 and libs install with brew.
OpenExr libs installed is v2.0.1.
The compiler (clang) stop with this message:

```
Readers/ExrDecoder.cpp:207:13: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
            delete _inputfile;
            ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:209:26: error: allocation of incomplete type 'Imf::InputFile'
        _inputfile = new Imf::InputFile(ba.constData());
                         ^~~~~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:251:57: error: member access into incomplete type 'Imf::InputFile'
        const Imf::ChannelList& imfchannels = _inputfile->header().channels();
                                                        ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:289:49: error: member access into incomplete type 'Imf::InputFile'
        const Imath::Box2i& datawin = _inputfile->header().dataWindow();
                                                ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:290:49: error: member access into incomplete type 'Imf::InputFile'
        const Imath::Box2i& dispwin = _inputfile->header().displayWindow();
                                                ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:301:35: error: member access into incomplete type 'Imf::InputFile'
        double aspect = _inputfile->header().pixelAspectRatio();
                                  ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:324:9: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
        delete _inputfile;
        ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:350:5: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
    delete _inputfile;
    ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:355:45: error: member access into incomplete type 'Imf::InputFile'
    const Imath::Box2i& dispwin = _inputfile->header().displayWindow();
                                            ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:356:45: error: member access into incomplete type 'Imf::InputFile'
    const Imath::Box2i& datawin = _inputfile->header().dataWindow();
                                            ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:398:23: error: member access into incomplete type 'Imf::InputFile'
            _inputfile->setFrameBuffer(fbuf);
                      ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:399:23: error: member access into incomplete type 'Imf::InputFile'
            _inputfile->readPixels(exrY);
                      ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
3 warnings and 9 errors generated.
make: *** [build_Powiter/release/.obj/ExrDecoder.o] Error 1
```
